<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
     <Description>ASP.NET Core Http integration for MiddleMan.Zero providing automatic conversion of Result objects to IResult with appropriate HTTP status codes.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../MiddleMan.Zero.Abstractions/MiddleMan.Zero.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
