<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MiddleMan.Zero.AspNetCore.Http\MiddleMan.Zero.AspNetCore.Http.csproj" />
    <ProjectReference Include="..\..\src\MiddleMan.Zero\MiddleMan.Zero.csproj" />
    <ProjectReference Include="..\..\src\MiddleMan.Zero.Abstractions\MiddleMan.Zero.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="MiddleMan.Zero.AspNetCore.Http" />
    <Using Include="MiddleMan.Zero.Abstractions" />
  </ItemGroup>

</Project>
