<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiddleMan.Zero.Abstractions\MiddleMan.Zero.Abstractions.csproj" />
    <ProjectReference Include="..\MiddleMan.Zero\MiddleMan.Zero.csproj" />
  </ItemGroup>

</Project>
